### ISSUE TITLE
Automatic text selection after clicking on a link

### ISSUE THREAD

**Issue by jarun** [linvinus/AltYo#47] opened 2016-03-27 12:03 UTC
Hi,

Here's an [image](http://i.imgur.com/8q2oUyx.png) to give a context.

Steps to reproduce:
While using AltYo in drop-down mode:
1. `Ctrl-left click` on a link to open the URL in browser
2. Frequently, the cursor goes into an auto-text selection mode and keeps selecting text till you click somewhere on the terminal.

Please let me know if you need any other information.

**Comment by linvinus** [comment] 2016-03-27 20:06
hi, which version libvte you are using? `ldd /usr/bin/altyo | grep libvte`
which linux distribution ?

**Comment by jarun** [comment] 2016-03-28 01:32
~$ ldd /usr/bin/altyo | grep libvte
 	libvte2_90.so.9 => /usr/lib/libvte2_90.so.9 (0x00007f98ec95a000)
    ~$ cat /etc/issue
    Ubuntu 14.04.4 LTS \n \l
    ~$ uname -a
    Linux tux 4.3.0-040300-generic #201511020949 SMP Mon Nov 2 14:50:44 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by linvinus** [comment] 2016-03-28 06:12
hi, thanks.
looks like you have customized config.
could you reset settings to default? 
in settings dialog press "revert"
your current settings will be saved in file  ~/.config/altyo/config.ini.bak
so if reset doesn't help, you may rollback config, just replace ~/.config/altyo/config.ini with ~/.config/altyo/config.ini.bak

**Comment by jarun** [comment] 2016-03-28 13:37
Hi,

With default settings it works fine. I have uploaded both the custom and fresh ones. Find them [here](https://app.box.com/s/h4gyo8mzv421471r58095hq4s50tkkip).

Please let me know which setting is causing this issue.

**Comment by linvinus** [comment] 2016-03-28 15:04
i expect that problem in `terminal_url_regexps` , but it is the same.
as i can see you have custom 
1) shell (fish) 
2) command to upen urls (/usr/share/iron/iron)
3) terminal_scrollback_lines=100000

all others should not create such problem 
could you change this settings one by one and then check is problem occur or not?

**Comment by jarun** [comment] 2016-03-28 15:18
I tried with firefox. This happens when `browser.tabs.loadDivertedInBackground` is set to `false` in about:config.
Not issue when the value is `true`.

**Comment by jarun** [comment] 2016-03-28 15:25
For the time being I am using this [extension](https://chrome.google.com/webstore/detail/force-background-tab/gidlfommnbibbmegmgajdbikelkdcmcl?hl=en).

Also tested that LXTerminal doesn't have any issues.

It would be great if there's a fix.

**Comment by linvinus** [comment] 2016-03-28 17:18
thank you for research of this problem, you are right this behavior is incorrect, i will try to find what is going  wrong

**Comment by jarun** [comment] 2016-03-28 17:37
Hey, no problem! AltYo saves me a few hours everyday. :)

**Comment by jarun** [comment] 2016-03-29 14:31
I have bad news, I'm afraid. I am noting the problem with the extension installed too.

I have already tried using bash and changing the scrollback to 10000. These are not causing it either.

**Comment by linvinus** [comment] 2016-04-01 07:17
hi, i don't understand which setting cause the problem? or for now you are not sure?

**Comment by jarun** [comment] 2016-04-01 07:57
Hi,

I am not sure. This is happening with tabs in background as well.

So:

1) shell (fish) - same issue with bash
2) command to upen urls (/usr/share/iron/iron) - same issue with Firefox
3) terminal_scrollback_lines=100000 - same issue after changing scrollback to 10000

**Comment by linvinus** [comment] 2016-04-19 09:24
jarun, hi.
i still can't reproduce this bug.

LXTerminal - Is not good example, because it use gtk2 and old libvte, so nothing common with altyo.
can you check in gnome-terminal 3 ?

**Comment by jarun** [comment] 2016-04-19 12:43
I switched to Manjaro LXQt, and I am not seeing this issue anymore. I copied the same config from Ubuntu. Feel free to close this issue.

**Comment by linvinus** [comment] 2016-04-19 18:19
i can't reproduce this, and it seems that only one user have such problem, so i will close this bug.
if anyone will have same issue, please reopen

**Closed by linvinus** 2016-04-19 18:19 UTC
